---
# ── Git default config ──────────────────────────────────────
- name: Set git default branch name
  community.general.git_config:
    name: init.defaultBranch
    value: main
    scope: global
  become: true
  become_user: "{{ target_user }}"

- name: Set git user name
  community.general.git_config:
    name: user.name
    value: "ViktorKarl"
    scope: global
  become: true
  become_user: "{{ target_user }}"

- name: Set git user email
  community.general.git_config:
    name: user.email
    value: "viktorkg98@gmail.com"
    scope: global
  become: true
  become_user: "{{ target_user }}"
