---
# ── kubectl ─────────────────────────────────────────────────
- name: Get latest stable version of kubectl
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: k8s_version

- name: Download and install kubectl binary
  get_url:
    url: "https://dl.k8s.io/release/{{ k8s_version.content | trim }}/bin/linux/{{ deb_arch }}/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
    owner: root
    group: root
