name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_envirioment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Ansible
      - name: Install Ansible
        run: |
          sudo apt-get update -q
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.general
  # Lint
      - name: ShellCheck
        run: shellcheck *.sh


      # Run playbooks
      - name: Run set-up.yaml
        run: ansible-playbook set-up.yaml --become -v

      - name: Run devops-tools.yaml
        run: ansible-playbook devops-tools.yaml --become -v

      # Verify
      - name: Verify tools
        run: |
          for cmd in git curl jq kubectl helm terraform az podman; do
            command -v "$cmd" && echo "✅ $cmd" || { echo "❌ $cmd missing"; exit 1; }
          done
          echo "✅ All good!"
